[T-15616]: adding semantic release workflow.
pokt-foundation/relay-meter pull request #32
Opened 2022-11-14 12:36 UTC by olakunle-pokt

2022-11-14 12:51 UTC, WesleyCharlesBlake requested changes

2022-11-14 12:51 UTC, WesleyCharlesBlake commented on .github/workflows/tag_and_release.yml
> +          use_github_release_notes: true
please add a new line

2022-11-14 16:55 UTC, olakunle-pokt commented on .github/workflows/tag_and_release.yml
> +          use_github_release_notes: true
This has been added.

2022-11-21 10:46 UTC, WesleyCharlesBlake approved these changes

2022-11-21 11:58 UTC, closed without merging