T-18302 PHD V1 - Update E2E tests for Relay Meter
pokt-foundation/relay-meter pull request #53
Opened 2023-02-01 19:38 UTC by commoddity

The E2E tests for relay meter were no longer working and has to be updated to work with PHD V1 endpoints. I updated them to work with the new test Docker DB image which uses the latest DB schema from the DB driver repo. This has the advantage of simplifying the test code significantly.

2023-02-02 00:16 UTC, pablocampogo requested changes, later dismissed
Small change

2023-02-02 00:16 UTC, pablocampogo commented on api/server.go
> +	fmt.Println("FIRING APP LATENCY")
Hi hello, this shouldn't be here

2023-02-02 02:31 UTC, commoddity commented on api/server.go
> +	fmt.Println("FIRING APP LATENCY")
☠️😵☠️

2023-02-07 03:07 UTC, ricantar approved these changes
Ty mate

2023-02-07 03:07 UTC, ricantar commented on cmd/apiserver/main.go
> +	fmt.Println("HERE", fmt.Sprintf("%s/load_balancer", b.phdBaseURL))
Could you remove this please?

2023-02-07 03:08 UTC, merged