V2 portal db types
pokt-foundation/relay-meter pull request #87
Opened 2023-06-30 03:35 UTC by commoddity

2023-08-10 16:37 UTC, ricantar commented on api/server.go
> +	// TODO: should we change the path from endpoints to portal_apps?
Yes, but in the next iteration

2023-08-10 16:38 UTC, ricantar commented
You can point this into master. Relay-meter does not have an staging env 😅

2023-08-29 15:09 UTC, commoddity commented on api/meter.go
> +	Count     RelayCounts              `json:"Count"`
JSON tags explicitly set to avoid disruption to other repos that have not had their struct field names updated yet.

2023-08-29 15:26 UTC, pablocampogo requested changes

2023-08-29 15:26 UTC, pablocampogo commented on db/influx.go
> +package db
Why is this file added?

2023-08-29 15:28 UTC, pablocampogo approved these changes

2023-08-29 15:34 UTC, merged