feat: Implement private ip
pokt-foundation/relay-meter pull request #91
Opened 2023-07-12 21:57 UTC by ricantar

- Implement private IP connection to GCP
- Remove influx from codebase

2023-07-12 22:07 UTC, commoddity reviewed
This looks good to me for now but I will leave to someone else to approve who is more up to date on Relay Meter.

2023-07-12 23:27 UTC, pablocampogo requested changes
Just some minor comments

2023-07-12 23:27 UTC, pablocampogo commented on .github/workflows/docker-gar.yml
>        - name: Build the Docker test stack
Also comment the docker stack build, this just takes unnecessary time

2023-07-12 23:27 UTC, pablocampogo commented on .github/workflows/lint-test.yml
>          run: docker-compose -f ./testdata/docker-compose.test.yml up -d --build
Same comment here

2023-07-12 23:27 UTC, pablocampogo commented on e2e_test.go
>  		mainBucket, main1mBucket, orgID,
U can delete bucket names and org ids of this structure too

2023-07-13 00:46 UTC, pablocampogo approved these changes, later dismissed

2023-07-13 00:59 UTC, pablocampogo approved these changes

2023-07-13 01:00 UTC, merged